dnsServers:
  - 178.22.122.100
  - 185.51.200.2
  - 192.104.158.78
  - 194.104.158.48
  - 172.29.0.100
  - 172.29.2.100
  - 10.202.10.202
  - 10.202.10.102
  - 185.55.226.26
  - 185.55.225.25
  - 185.55.224.24
  - 10.202.10.10
  - 10.202.10.11
  - 37.27.41.228
  - 87.107.52.11
  - 87.107.52.13
  - 5.202.100.100
  - 5.202.100.101
  - 94.103.125.157
  - 94.103.125.158
  - 141.11.45.91
  - 37.32.5.60
  - 37.32.5.61
